# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('sectionid', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
