# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseArrange.Section'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='status',
            field=models.CharField(choices=[('s', 'student'), ('t', 'teacher'), ('m', 'manager')], max_length=1),
        ),
    ]
