# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0002_auto_20170613_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='sectionid',
            field=models.IntegerField(default=0),
        ),
    ]
