# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0003_auto_20170613_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('ddl', models.DateField()),
                ('reference', models.CharField(max_length=30)),
                ('courseid', models.CharField(max_length=15)),
                ('comment', models.FileField(upload_to='uploads/assignment/')),
            ],
        ),
        migrations.CreateModel(
            name='assignment_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentid', models.CharField(max_length=15)),
                ('studentid', models.CharField(max_length=15)),
                ('file_path', models.FileField(upload_to='uploads/assignment/')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
