# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0004_assignment_assignment_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('file_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=40)),
                ('file_path', models.FileField(upload_to='uploads/assignment/')),
                ('update_time', models.TimeField()),
                ('download_times', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('flag_top', models.IntegerField()),
            ],
        ),
    ]
