# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-06-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
