# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0006_auto_20170620_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_store',
            old_name='file_path',
            new_name='file_name',
        ),
    ]
