# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareSource', '0009_auto_20170620_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
