# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_best',
            field=models.IntegerField(default=0),
        ),
    ]
