# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_post_is_best'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
    ]
