# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20170616_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
    ]
