# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSelection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectiontime',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='selectiontime',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
