# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseSelection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='section',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='student',
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
    ]
