# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0004_auto_20170618_0219'),
        ('courseArrange', '0001_initial'),
        ('courseSelection', '0002_auto_20170618_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='condition',
            new_name='selection_condition',
        ),
        migrations.AlterField(
            model_name='selection',
            name='drop_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='select_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set([('section', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='selectiontime',
            unique_together=set([('semester', 'year', 'selection_round')]),
        ),
    ]
