# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseSelection', '0003_auto_20170620_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumdemand',
            name='compulsory',
        ),
    ]
