# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('instru_id', models.CharField(max_length=20)),
                ('q_type', models.CharField(choices=[('xz', 'C'), ('pd', 'P')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=400)),
                ('difficulty', models.CharField(choices=[('e', 'Easy'), ('m', 'Middle'), ('h', 'Hard')], max_length=1)),
            ],
        ),
    ]
