# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('e', 'Easy'), ('m', 'Middle'), ('h', 'Hard')], max_length=1)),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'closed')], max_length=1)),
                ('limit_time', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('xz', 'C'), ('pd', 'P')], max_length=2)),
                ('title', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'closed')], max_length=1)),
                ('answer', models.CharField(max_length=1)),
                ('choice1', models.CharField(max_length=400, null=True)),
                ('choice2', models.CharField(max_length=400, null=True)),
                ('choice3', models.CharField(max_length=400, null=True)),
                ('choice4', models.CharField(max_length=400, null=True)),
                ('difficulty', models.CharField(choices=[('e', 'Easy'), ('m', 'Middle'), ('h', 'Hard')], max_length=1)),
                ('test_point', models.CharField(max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Instructor')),
                ('paper', models.ManyToManyField(to='onlinetest.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=1)),
                ('mark', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetest.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_time', models.DateTimeField(auto_now=True)),
                ('tot_mark', models.IntegerField(null=True)),
                ('xz_mark', models.IntegerField(null=True)),
                ('pd_mark', models.IntegerField(null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetest.Paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicInfo.Student')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetest.Sheet'),
        ),
    ]
