# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0005_auto_20170615_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1),
        ),
    ]
