# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0006_auto_20170615_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='sheet',
        ),
    ]
