# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0007_remove_reply_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='instru_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='instru_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_point',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='precourse',
        ),
        migrations.AddField(
            model_name='course',
            name='precourse',
            field=models.ManyToManyField(to='onlinetest.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tot_cred',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='takes',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.DeleteModel(
            name='Test_point',
        ),
    ]
