# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0010_auto_20170621_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='precourse',
        ),
        migrations.RemoveField(
            model_name='coursecandiate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecandiate',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructorbusytime',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorbusytime',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='major',
            name='department',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='course',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='precourse',
        ),
        migrations.RemoveField(
            model_name='sectimeclassroom',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='sectimeclassroom',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectimeclassroom',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='section',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='section',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AlterField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Course'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Instructor'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Instructor'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicInfo.Student'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCandiate',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorBusyTime',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Prereq',
        ),
        migrations.DeleteModel(
            name='SecTimeClassroom',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
