# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomequipment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroomequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.ManyToManyField(to='basicInfo.Equipment'),
        ),
        migrations.DeleteModel(
            name='ClassroomEquipment',
        ),
    ]
