# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseArrange', '0001_initial'),
        ('basicInfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseArrange.Section'),
        ),
        migrations.AddField(
            model_name='takes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicInfo.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Major'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Department'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Department'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicInfo.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='precourse',
            field=models.ManyToManyField(to='basicInfo.Course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.ManyToManyField(to='basicInfo.Equipment'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('building', 'room_number')]),
        ),
    ]
