# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0002_auto_20170602_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
