# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0004_auto_20170604_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='section',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='photo_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('building', 'room_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set([('day', 'start_time', 'end_time')]),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
    ]
