# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseArrange', '0001_initial'),
        ('basicInfo', '0005_auto_20170608_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseArrange.Section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='method',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicInfo.Student'),
        ),
    ]
