# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0006_auto_20170609_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduate',
            field=models.IntegerField(null=True),
        ),
    ]
