# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0009_auto_20170618_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
