# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0010_auto_20170618_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='nickName',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='nickName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nickName',
        ),
    ]
