# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0011_auto_20170619_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='precourse',
            field=models.ManyToManyField(to='basicInfo.Course'),
        ),
    ]
