# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseArrange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecandiate',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecandiate',
            name='classroom_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorbusytime',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorbusytime',
            name='end_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorbusytime',
            name='start_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
